name: flutter_hidco
description: Hidco with Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  carousel_pro: ^1.0.0
  carousel_slider: ^2.2.1
  webview_flutter: 0.3.22+1
  photo_view: 0.10.0
  url_launcher: ^4.1.0


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/h_tipi_anasayfa.png
    - assets/images/banka.png
    - assets/images/bayiler.png
    - assets/images/blog.png
    - assets/images/hakkimizda.png
    - assets/images/iletisim.png
    - assets/images/insankaynaklari.png
    - assets/images/shop.png
    - assets/images/sosyalmedya.png
    - assets/images/urunler.png
    - assets/images/logo.png
    - assets/images/h2_sol.png
    - assets/images/h2.jpg
    - assets/images/izmirsalter.png
    - assets/icons/blog_icon.png
    - assets/icons/banka_icon.png
    - assets/icons/bayiler_icon.png
    - assets/icons/hakkimizda_icon.png
    - assets/icons/iletisim_icon.png
    - assets/icons/insankaynaklari_icon.png
    - assets/icons/shop_icon.png
    - assets/icons/sosyalmedya_icon.png
    - assets/icons/urunler_icon.png
    - assets/icons/drawler_icon.png
    - assets/images/izmirAta.png
    - assets/images/izmirMera.png
    - assets/images/izmirMotorcular.png
    - assets/images/izmirRultek.png
    - assets/images/izmirSalt.jpg
    - assets/images/ankaraRedmak.jpg
    - assets/images/ankaraSayic.png
    - assets/images/antepCayisagasi.jpg
    - assets/images/istanbulBogazici.png
    - assets/images/Ankara.jpg
    - assets/images/istanbul.jpg
    - assets/images/denizli.jpg
    - assets/images/antep.jpg
    - assets/images/izmir.jpg
    - assets/images/kosgeb.png
    - assets/icons/instagram.jpg
    - assets/icons/facebook.jpg
    - assets/icons/linkedin.png
    - assets/icons/pinterest.png
    - assets/icons/twitter.png
    - assets/images/backgroundtemplete.png
    - assets/icons/genisbayiicon.PNG
    - assets/icons/hizliteslimaticon.PNG
    - assets/icons/kaliteicon.PNG
    - assets/icons/musteriicon.PNG
    - assets/icons/tecrubeicon.PNG
    - assets/icons/uygunfiyaticon.PNG
    - assets/icons/adresicon.PNG
    - assets/icons/telefonicon.PNG
    - assets/icons/mailicon.PNG
    - assets/images/isbankasiLogo.jpg
    - assets/images/pttbankLogo.jpg
    - assets/images/isbankasiLogo.PNG
    - assets/images/pttbankLogo.PNG
    - assets/images/insankaynaklari1.jpg
    - assets/images/insankaynaklari2.png
    - assets/images/insankaynaklarihead.PNG
    - assets/images/process1.png
    - assets/images/process2-1.png
    - assets/images/process3-1.png
    - assets/images/adim01.PNG
    - assets/images/adim02.PNG
    - assets/images/adim03.PNG
    - assets/images/hakkimizda1.png
    - assets/images/h3.jpg
    - assets/images/h3_sol.png
    - assets/images/h4.jpg
    - assets/images/h4_sol.png
    - assets/images/h5.jpg
    - assets/images/h5_sol.png
    - assets/images/h6.jpg
    - assets/images/h6_sol.png
    - assets/images/h7.jpg
    - assets/images/h7_sol.png
    - assets/images/Hidesan-ayaklı-aktarma-redüktör.jpg
    - assets/images/Hidesan-ayaklı-redüktör.jpg
    - assets/images/Hidesan-flanşlı-aktarma-redüktör.jpg
    - assets/images/Hidesan-flanşlı-redüktör.jpg
    - assets/images/hTipiUrun.jpg
    - assets/images/K-TİPİ-REDÜKTÖR.png
    - assets/images/KM3-KIYMA-REDÜKTÖR.jpg
    - assets/images/T-TİPİ-FLANŞLI-REDÜKTÖR.jpg
    - assets/images/T-TİPİ-REDÜKTÖR.png
    - assets/images/hidesan-ayakli-aktarma-tablo.PNG
    - assets/images/hidesan-ayakli.PNG
    - assets/images/hidesan-ayakli-aktarma.PNG
    - assets/images/hidesan-ayakli-tablo.PNG
    - assets/images/hidesan-flansli.PNG
    - assets/images/hidesan-flansli-tablo.PNG
    - assets/images/hidesan-flansli-aktarma.PNG
    - assets/images/hidesan-flansli-aktarma-tablo.PNG
    - assets/images/k-tip.PNG
    - assets/images/k-tip-tablo.PNG
    - assets/images/t-tip-ayakli.PNG
    - assets/images/t-tip-ayakli-tablo.PNG






  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
